apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ksymrdij7-nodejs 
  janus-idp.io/tekton: ksymrdij7-nodejs
  backstage.io/kubernetes-id: ksymrdij7-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ksymrdij7-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  